### ISSUE TITLE
Compilation of wrong types should not proceed

### ISSUE THREAD

**Issue by paulmillr** [baptistedonaux/brunch-typescript#11]
Try this:

```
let myAdd: (baseValue:number, increment:number) => number =
    function(x, y) { return x + y; };

exports.myAdd = myAdd;
exports.zzz = myAdd(5, '2');
```

It seems to go through. Not sure why.

**Comment by baptistedonaux** [comment]
When I built it with TypeScript, I have this error :

```bash
$ tsc tmp.ts
tmp.ts(4,1): error TS2304: Cannot find name 'exports'.
tmp.ts(5,1): error TS2304: Cannot find name 'exports'.
tmp.ts(5,24): error TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.
```

**Comment by baptistedonaux** [comment]
For me, it's a TypeScript failed.

The ```myAdd``` second args is a number, not a string (```myAdd(5, '2');```).

**Comment by paulmillr** [comment]
@baptistedonaux what do you mean? I install brunch-typescript, then create `app/file.ts` with the content.

Brunch should not let Typescript compile it since this is a definite TypeError. But the compilation is successful and goes through.

**Comment by baptistedonaux** [comment]
@paulmillr I see it quickly.

@colinbate Maybe do you have an idea ?

**Comment by colinbate** [comment]
I would have expected the typescript compiler to have failed via the API, but I guess it still creates output. I will look into this later this afternoon.

**Comment by baptistedonaux** [comment]
Scenario can be re-played on this branch https://github.com/baptistedonaux/brunch-typescript/tree/test-issue-11

**Comment by colinbate** [comment]
Created a PR to fix this. (#12)

**Comment by baptistedonaux** [comment]
@paulmillr 1.8.2 released with AWS fix by @colinbate
