### ISSUE TITLE
Usage a bit unclear / incomplete.

### ISSUE THREAD

**Issue by bigp** [baptistedonaux/brunch-typescript#16]
Hi there,

I was trying to hunt down a brunch plugin to support typescript and this repo looks like the most active. But, one thing I noticed is that although the Usage section goes in great detail on how to install and configure the plugin, there's no mention or examples of how to set the files pattern (joinTo) to watch the TypeScript files.

Can both *.ts and *.js files be watched with file patterns? Something like:

    files: {
        javascripts: { joinTo: {
           'app.js': /^app\/[a-zA-Z0-9_\-]*\.(js|ts)/
        }
     },

**Comment by baptistedonaux** [comment]
Hi @bigp ,

It's probably an issue relative at brunch core (cc @paulmillr).

```brunch-typescript```supports compilation of TypeScript files, so only *.ts. I think that your pattern must be anything like this : 
```
/^app\/[a-zA-Z0-9_\-]*\.t$/
```

**Comment by colinbate** [comment]
@bigp you can compile `.js` files, but you will need to update the plugin config. The default pattern for `brunch-typescript` is `/\.ts(x)?$/`. If you wanted, you could add this to your `brunch-config` file, in addition to whatever changes you need to make to your `joinTo`. Although I wouldn't put the extensions in the `joinTo` unless you have other types of script files bundling into another file.

```js
plugins: {
  brunchTypescript: {
    pattern: /\.[tj]s(x)?$/
  }
}
```

**Comment by colinbate** [comment]
@bigp I'm going to close this as we haven't heard back. If you have any further concerns you can open a new issue or reopen this one.
