### ISSUE TITLE
Support Typescript 2.0 beta

### ISSUE THREAD

**Issue by edevil** [baptistedonaux/brunch-typescript#19]
Is it possible to use the new Typescript 2.0 beta?

https://blogs.msdn.microsoft.com/typescript/2016/07/11/announcing-typescript-2-0-beta/

**Comment by colinbate** [comment]
I have some time in the next couple weeks so I'll take a look.

**Comment by jmls** [comment]
were you able to have a look ? ;)

**Comment by baptistedonaux** [comment]
@colinbate I think there isn't difference between stable and beta API. I will check quickly.

**Comment by colinbate** [comment]
No I didn't get the chance, and I still haven't. However, I will play with it when I get a chance over the next couple evenings. The RC is out now, so I will use that. I'll start with basic 2.0 support like we have with 1.8 and then I'll look at what would be involved in using the TypeScript service.

However, I won't have a lot of time to devote to that for a few weeks yet.

**Comment by colinbate** [comment]
OK, I've updated to reference TypeScript 2.0.x. I've also made it possible to go back to ignoring all of the TS errors until we can sort out proper support for that. Once version 2.0.0 of this library is published, you should be good to go.

**Comment by baptistedonaux** [comment]
@colinbate Thanks for your feedback. I have pushed a new release ```2.0.0``` and released this version on NPM.

Thanks !
