### ISSUE TITLE
When using wildcards, not all the inputs get merged into a single file

### ISSUE THREAD

**Issue by Jojatekok** [baptistedonaux/brunch-typescript#2]
__Solution:__

Instead of executing multiple tsc --out commands for a single output (https://github.com/baptistedonaux/brunch-typescript/blob/master/index.js#L48), group input files by outputs.

For example, instead of executing

```
tsc --out bigfile.js part1.ts
tsc --out bigfile.js part2.ts
tsc --out bigfile.js part3.ts
```

Execute

```
tsc --out bigfile.js part1.ts part2.ts part3.ts
```

**Comment by baptistedonaux** [comment]
Hi, thank you for your feedback. It's great, people may need of this feature.

Do you want send a pull request or waiting my implementation ?

**Comment by Jojatekok** [comment]
I don't have any experience in developing npm packages, so I'm currently waiting for an implementation. By the way, thanks for maintaining the only usable Brunch plugin for TypeScript! :)

**Comment by baptistedonaux** [comment]
Great ! I will try to add this feature quickly. I ping you when the feature will be developed.

**Comment by Jojatekok** [comment]
That's absolutely awesome, thanks! :+1:
Until then, I'll be using a batch file to build my TypeScript files, so no worries :)

**Comment by baptistedonaux** [comment]
brunch-typescript@1.6.1 supports now the many files building. The npm repository is already updated !
